# Generated by Django 5.1.4 on 2025-01-11 14:17

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('top_movies', models.CharField(blank=True, max_length=255)),
                ('top_series', models.CharField(blank=True, max_length=255)),
                ('top_music_albums', models.CharField(blank=True, max_length=255)),
                ('top_books', models.CharField(blank=True, max_length=255)),
                ('top_podcasts', models.CharField(blank=True, max_length=255)),
                ('top_miscellaneous', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
