# Generated by Django 5.1.4 on 2025-01-28 13:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_options_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='nederlearn_logo.webp', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
