# Generated by Django 5.1.4 on 2025-01-28 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_excerpt_alter_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='blogpost_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
