# Generated by Django 4.2 on 2025-02-04 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blogpost_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="blogpost_placeholder_x6ckko",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
